services:
  - type: web
    name: hk-restaurant-database
    runtime: node
    buildCommand: npm install && npm run build && cd client && npm install && npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true